name = "Text Only"
license = "GNU3.0"
licenselink = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme/blob/master/LICENSE"
description = ""

[author]
  name = "Blain Smith"
  homepage = "https://blainsmith.com"
